"""Add fields to SoldProduct model

Revision ID: 30c7ec425ef3
Revises: ac0d13dd9245
Create Date: 2024-10-11 22:28:58.291537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c7ec425ef3'
down_revision = 'ac0d13dd9245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sold_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('karat', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gold_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('weight_range', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('barcode', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sold_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('barcode')
        batch_op.drop_column('weight_range')
        batch_op.drop_column('gold_type')
        batch_op.drop_column('karat')
        batch_op.drop_column('category')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
